from datetime import datetime
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from ..database import get_db
from .. import models, schemas, auth, prediction

router = APIRouter(prefix="/api/reports", tags=["Reports"])

@router.get("", response_model=List[schemas.ReportResponse])
def get_reports(
    project_id: Optional[int] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(auth.get_current_user)
):
    query = db.query(models.Report)
    if project_id:
        query = query.filter(models.Report.project_id == project_id)
    return query.order_by(models.Report.created_at.desc()).all()

@router.post("", response_model=schemas.ReportResponse, status_code=status.HTTP_201_CREATED)
def generate_report(
    report_in: schemas.ReportCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(auth.require_manager_or_above)
):
    project = db.query(models.Project).filter(models.Project.id == report_in.project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
        
    # Get delay prediction metrics to include
    pred = prediction.predict_delay(project, db)
    
    # Get all milestones
    milestones = db.query(models.Milestone).filter(models.Milestone.project_id == project.id).all()
    completed_ms = [m for m in milestones if m.status == "Completed"]
    pending_ms = [m for m in milestones if m.status != "Completed"]
    
    # Get recent alerts
    alerts = db.query(models.Alert).filter(
        models.Alert.project_id == project.id,
        models.Alert.status == "unread"
    ).all()
    
    # Build dynamic markdown report content
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    
    report_title = f"{report_in.report_type.upper()} REPORT: {project.name}"
    
    content = f"""# {report_title}
**Ministry of Statistics and Programme Implementation (MoSPI)**
*Generated by: {current_user.name} ({current_user.role}) | Timestamp: {now_str} UTC*
*Project Reference: {project.project_code}*

---

## 1. Executive Summary
This project is currently classified under the status **{project.status}** with a calculated risk profile of **{project.risk_level}** (AI Predicted Delay Probability: **{pred['risk_score']}%**).
Physical work completion stands at **{project.progress:.1f}%**, and financial disbursement is currently **{project.financial_progress:.1f}%**.

## 2. Financial Overview
- **Approved Budget**: ₹{project.budget:,.2f} Crores
- **Cumulative Expenditure**: ₹{project.amount_spent:,.2f} Crores
- **Fund Utilization Rate**: {project.financial_progress:.1f}%
- **Available Balance**: ₹{(project.budget - project.amount_spent):,.2f} Crores

"""

    # Add specific contents depending on report type
    if report_in.report_type == "Delay Report":
        content += f"""## 3. Schedule & Delay Intelligence
- **Planned Start Date**: {project.start_date.strftime('%Y-%m-%d')}
- **Expected Completion Target**: {project.expected_end_date.strftime('%Y-%m-%d')}
- **AI Predicted Delay Duration**: {pred['expected_delay']} days

### Primary Contributing Factors:
"""
        for factor in pred["contributing_factors"]:
            content += f"- **Factor**: {factor}\n"
            
        content += "\n### Milestone Delays:\n"
        for m in pending_ms:
            if m.status == "Delayed" or (m.planned_date < datetime.utcnow()):
                days = (datetime.utcnow() - m.planned_date).days
                content += f"- **{m.name}**: Overdue by {days} days (planned deadline was {m.planned_date.strftime('%Y-%m-%d')}).\n"
                
    elif report_in.report_type == "Risk Report":
        content += f"""## 3. Risk Profile & Anomaly Matrix
- **Overall Project Vulnerability**: {project.risk_level.upper()}
- **AI Analytics Confidence Score**: 89%

### Active System Warnings:
"""
        if alerts:
            for alert in alerts:
                content += f"- **[{alert.severity.upper()}]** {alert.message}\n"
        else:
            content += "- No critical unread alerts registered in database.\n"
            
        content += "\n### Recommended Risk Mitigation Actions:\n"
        for action in pred["recommended_actions"]:
            content += f"- **Recommendation**: {action}\n"
            
    else:
        # Default status/executive report
        content += f"""## 3. Milestone Completion Metrics
- **Total Milestones Defined**: {len(milestones)}
- **Completed**: {len(completed_ms)}
- **Pending/Delayed**: {len(pending_ms)}

### Milestone Details:
"""
        for m in milestones:
            act_date = m.actual_date.strftime('%Y-%m-%d') if m.actual_date else "N/A"
            content += f"- **{m.name}** | Target: {m.planned_date.strftime('%Y-%m-%d')} | Status: `{m.status}` | Completed: {act_date}\n"
            
    content += f"""
---
## 4. Platform Action Plan & Approval
1. **Contractor Meeting**: Scheduled review regarding low physical output.
2. **Funds Disbursement**: Restrict subsequent fund releases to verified milestones.
3. **Escalation**: Report submitted automatically to MoSPI project-monitoring desk.

*Report signed off by ProjectPulse AI Intelligence Engine.*
"""

    db_report = models.Report(
        project_id=report_in.project_id,
        report_type=report_in.report_type,
        content=content,
        generated_by_id=current_user.id
    )
    db.add(db_report)
    db.commit()
    db.refresh(db_report)
    
    # Audit log
    db.add(models.AuditLog(
        user_id=current_user.id,
        action="Report Generated",
        entity_type="project",
        entity_id=project.id,
        details=f"Generated {report_in.report_type} for project {project.project_code}."
    ))
    db.commit()
    
    return db_report
